### ISSUE TITLE
Add zunoPTIConfigUART description

### ISSUE THREAD

**Issue by PoltoS** [Z-Wave-Me/Z-Uno-Reference#3]
Add zunoPTIConfigUART description with a link to https://z-uno.z-wave.me/Reference/

**Comment by amatilda** [comment]
#define PTI_PIN         TX2     // TX2 is default USB CDC pin
                                // You are able to sketch ANY ZUno pin
#define PTI_BAUDRATE    230400L // The minimal baud is 230400
                                // The maximum baud is 1.6MBit
  
  if(zunoPTIConfigUART(PTI_PIN, PTI_BAUDRATE)){
    Serial0.println("[Done]");
  } else {
    Serial0.println("[Failed]");
  }

**Comment by PoltoS** [comment]
Sorry, the link should be here: https://z-uno.z-wave.me/Reference/ and not on  https://z-wave.me/products/zniffer/. Please add

**Comment by amatilda** [comment]
https://z-uno.z-wave.me/Reference/zunoPTIConfigUART/

**Comment by PoltoS** [comment]
https://github.com/Z-Wave-Me/Z-Uno-Reference/commit/dede0437f2fe95e479c49886882da70e3b435b24
